name: Java Versioning/Deploy
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: "-Xmx8048m"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCOUNT_GITHUB_TOKEN }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'
          check-latest: false

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
#      - name: Generate Changelog
#        working-directory: ./java
#        run: mvn se.bjurr.gitchangelog:git-changelog-maven-plugin:2.1.0:git-changelog
#      - name: Commit Changelog
#        working-directory: ./java
#        run: |
#          git add CHANGELOG.md
#          git commit -m "docs: update changelog for version"
#          git push origin master
      - name: Setup Maven settings.xml
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
              "id": "central",
              "username": "${{ secrets.OSSRH_USERNAME }}",
              "password": "${{ secrets.OSSRH_TOKEN }}"
            }
            ]
      - name: Import GPG key
        env:
          GPG_PRIVATE_KEY: ${{ secrets.MAVEN_GPG_KEY }}
          GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        run: |
          echo "$GPG_PRIVATE_KEY" | base64 --decode | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Prepare Release
        working-directory: ./java
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
        run: |
          set -e
          mvn release:prepare \
          -DtagNameFormat=v@{project.version} \
          -Darguments="-Pnexus-release -DskipTests=true -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASSPHRASE }}"
      - name: Perform Release
        working-directory: ./java
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          MAVEN_OPTS: "-Xmx8096m"
        run: mvn release:perform -Pnexus-release -DskipTests=true
      - name: Push changes
        run: |
          set -e
          git push origin master
          git push origin --tags
